using System;

namespace ISO3166NL
{
    public class Land
    {
        public string Naam { get; private set; }
        public string TweeLetterCode { get; private set; }
        public string DrieLetterCode { get; private set; }
        public string NumeriekeCode { get; private set; }

        private Land(string naam, string tweeLetterCode, string drieLetterCode, string numeriekeCode)
        {
            Naam = naam;
            TweeLetterCode = tweeLetterCode;
            DrieLetterCode = drieLetterCode;
            NumeriekeCode = numeriekeCode;
        }

        public static readonly Land[] List = new[]
        {
            new Land("Afghanistan", "AF", "AFG", "004"),
            new Land("Albanië", "AL", "ALB", "008"),
            new Land("Algerije", "DZ", "DZA", "012"),
            new Land("Amerikaans-Samoa", "AS", "ASM", "016"),
            new Land("Andorra", "AD", "AND", "020"),
            new Land("Angola", "AO", "AGO", "024"),
            new Land("Anguilla", "AI", "AIA", "660"),
            new Land("Antarctica", "AQ", "ATA", "010"),
            new Land("Antigua en Barbuda", "AG", "ATG", "028"),
            new Land("Argentinië", "AR", "ARG", "032"),
            new Land("Armenië", "AM", "ARM", "051"),
            new Land("Aruba", "AW", "ABW", "533"),
            new Land("Australië", "AU", "AUS", "036"),
            new Land("Oostenrijk", "AT", "AUT", "040"),
            new Land("Azerbeidzjan", "AZ", "AZE", "031"),
            new Land("Bahama's", "BS", "BHS", "044"),
            new Land("Bahrein", "BH", "BHR", "048"),
            new Land("Bangladesh", "BD", "BGD", "050"),
            new Land("Barbados", "BB", "BRB", "052"),
            new Land("Wit-Rusland", "BY", "BLR", "112"),
            new Land("België", "BE", "BEL", "056"),
            new Land("Belize", "BZ", "BLZ", "084"),
            new Land("Benin", "BJ", "BEN", "204"),
            new Land("Bermuda", "BM", "BMU", "060"),
            new Land("Bhutan", "BT", "BTN", "064"),
            new Land("Bolivië, De Plurinationale Staat", "BO", "BOL", "068"),
            new Land("Bonaire, Sint Eustatius en Saba", "BQ", "BES", "535"),
            new Land("Bosnië en Herzegovina", "BA", "BIH", "070"),
            new Land("Botswana", "BW", "BWA", "072"),
            new Land("Bouveteiland", "BV", "BVT", "074"),
            new Land("Brazilië", "BR", "BRA", "076"),
            new Land("Brits Indische Oceaanterritorium", "IO", "IOT", "086"),
            new Land("Brunei", "BN", "BRN", "096"),
            new Land("Bulgarije", "BG", "BGR", "100"),
            new Land("Burkina Faso", "BF", "BFA", "854"),
            new Land("Burundi", "BI", "BDI", "108"),
            new Land("Kaapverdië", "CV", "CPV", "132"),
            new Land("Cambodja", "KH", "KHM", "116"),
            new Land("Kameroen", "CM", "CMR", "120"),
            new Land("Canada", "CA", "CAN", "124"),
            new Land("Kaaimaneilanden", "KY", "CYM", "136"),
            new Land("Centraal-Afrikaanse Republiek", "CF", "CAF", "140"),
            new Land("Tsjaad", "TD", "TCD", "148"),
            new Land("Chili", "CL", "CHL", "152"),
            new Land("China", "CN", "CHN", "156"),
            new Land("Kersteiland", "CX", "CXR", "162"),
            new Land("Cocoseilanden", "CC", "CCK", "166"),
            new Land("Colombia", "CO", "COL", "170"),
            new Land("Comoren", "KM", "COM", "174"),
            new Land("Congo-Brazzaville", "CG", "COG", "178"),
            new Land("Democratische Republiek Congo", "CD", "COD", "180"),
            new Land("Cookeilanden", "CK", "COK", "184"),
            new Land("Costa Rica", "CR", "CRI", "188"),
            new Land("Ivoorkust", "CI", "CIV", "384"),
            new Land("Kroatië", "HR", "HRV", "191"),
            new Land("Cuba", "CU", "CUB", "192"),
            new Land("Curaçao", "CW", "CUW", "531"),
            new Land("Cyprus", "CY", "CYP", "196"),
            new Land("Tsjechië", "CZ", "CZE", "203"),
            new Land("Denemarken", "DK", "DNK", "208"),
            new Land("Djibouti", "DJ", "DJI", "262"),
            new Land("Dominica", "DM", "DMA", "212"),
            new Land("Dominicaanse Republiek", "DO", "DOM", "214"),
            new Land("Ecuador", "EC", "ECU", "218"),
            new Land("Egypte", "EG", "EGY", "818"),
            new Land("El Salvador", "SV", "SLV", "222"),
            new Land("Equatoriaal-Guinea", "GQ", "GNQ", "226"),
            new Land("Eritrea", "ER", "ERI", "232"),
            new Land("Estland", "EE", "EST", "233"),
            new Land("Swaziland", "SZ", "SWZ", "748"),
            new Land("Ethiopië", "ET", "ETH", "231"),
            new Land("Falklandeilanden (Islas Malvinas)", "FK", "FLK", "238"),
            new Land("Faeröer Eilanden", "FO", "FRO", "234"),
            new Land("Fiji", "FJ", "FJI", "242"),
            new Land("Finland", "FI", "FIN", "246"),
            new Land("Frankrijk", "FR", "FRA", "250"),
            new Land("Frans-Guyana", "GF", "GUF", "254"),
            new Land("Frans-Polynesië", "PF", "PYF", "258"),
            new Land("Franse Zuidelijke en Antarctische Gebieden", "TF", "ATF", "260"),
            new Land("Gabon", "GA", "GAB", "266"),
            new Land("Gambia", "GM", "GMB", "270"),
            new Land("Georgië", "GE", "GEO", "268"),
            new Land("Duitsland", "DE", "DEU", "276"),
            new Land("Ghana", "GH", "GHA", "288"),
            new Land("Gibraltar", "GI", "GIB", "292"),
            new Land("Griekenland", "GR", "GRC", "300"),
            new Land("Groenland", "GL", "GRL", "304"),
            new Land("Grenada", "GD", "GRD", "308"),
            new Land("Guadeloupe", "GP", "GLP", "312"),
            new Land("Guam", "GU", "GUM", "316"),
            new Land("Guatemala", "GT", "GTM", "320"),
            new Land("Guernsey", "GG", "GGY", "831"),
            new Land("Guinee", "GN", "GIN", "324"),
            new Land("Guinee-Bissau", "GW", "GNB", "624"),
            new Land("Guyana", "GY", "GUY", "328"),
            new Land("Haïti", "HT", "HTI", "332"),
            new Land("Heard en MacDonaldeilanden", "HM", "HMD", "334"),
            new Land("Vaticaanstad", "VA", "VAT", "336"),
            new Land("Honduras", "HN", "HND", "340"),
            new Land("Hongkong, Speciale bestuurlijke regio van Volksrepubliek China", "HK", "HKG", "344"),
            new Land("Hongarije", "HU", "HUN", "348"),
            new Land("IJsland", "IS", "ISL", "352"),
            new Land("India", "IN", "IND", "356"),
            new Land("Indonesië", "ID", "IDN", "360"),
            new Land("Iran", "IR", "IRN", "364"),
            new Land("Irak", "IQ", "IRQ", "368"),
            new Land("Ierland", "IE", "IRL", "372"),
            new Land("Man-eiland", "IM", "IMN", "833"),
            new Land("Israël", "IL", "ISR", "376"),
            new Land("Italië", "IT", "ITA", "380"),
            new Land("Jamaica", "JM", "JAM", "388"),
            new Land("Japan", "JP", "JPN", "392"),
            new Land("Jersey", "JE", "JEY", "832"),
            new Land("Jordanië", "JO", "JOR", "400"),
            new Land("Kazachstan", "KZ", "KAZ", "398"),
            new Land("Kenia", "KE", "KEN", "404"),
            new Land("Kiribati", "KI", "KIR", "296"),
            new Land("Korea, Democratische Volksrepubliek (Noord-Korea)", "KP", "PRK", "408"),
            new Land("Korea, Republiek (Zuid-Korea)", "KR", "KOR", "410"),
            new Land("Koeweit", "KW", "KWT", "414"),
            new Land("Kirgizië", "KG", "KGZ", "417"),
            new Land("Laos", "LA", "LAO", "418"),
            new Land("Letland", "LV", "LVA", "428"),
            new Land("Libanon", "LB", "LBN", "422"),
            new Land("Lesotho", "LS", "LSO", "426"),
            new Land("Liberia", "LR", "LBR", "430"),
            new Land("Libië", "LY", "LBY", "434"),
            new Land("Liechtenstein", "LI", "LIE", "438"),
            new Land("Litouwen", "LT", "LTU", "440"),
            new Land("Luxemburg", "LU", "LUX", "442"),
            new Land("Macau, Speciale bestuurlijke regio van Volksrepubliek China", "MO", "MAC", "446"),
            new Land("Madagaskar", "MG", "MDG", "450"),
            new Land("Malawi", "MW", "MWI", "454"),
            new Land("Maleisië", "MY", "MYS", "458"),
            new Land("Maldiven", "MV", "MDV", "462"),
            new Land("Mali", "ML", "MLI", "466"),
            new Land("Malta", "MT", "MLT", "470"),
            new Land("Marshalleilanden", "MH", "MHL", "584"),
            new Land("Martinique", "MQ", "MTQ", "474"),
            new Land("Mauritanië", "MR", "MRT", "478"),
            new Land("Mauritius", "MU", "MUS", "480"),
            new Land("Mayotte", "YT", "MYT", "175"),
            new Land("Mexico", "MX", "MEX", "484"),
            new Land("Micronesia, Federale staten van", "FM", "FSM", "583"),
            new Land("Moldavië, Republiek", "MD", "MDA", "498"),
            new Land("Monaco", "MC", "MCO", "492"),
            new Land("Mongolië", "MN", "MNG", "496"),
            new Land("Montenegro", "ME", "MNE", "499"),
            new Land("Montserrat", "MS", "MSR", "500"),
            new Land("Marokko", "MA", "MAR", "504"),
            new Land("Mozambique", "MZ", "MOZ", "508"),
            new Land("Myanmar", "MM", "MMR", "104"),
            new Land("Namibië", "NA", "NAM", "516"),
            new Land("Nauru", "NR", "NRU", "520"),
            new Land("Nepal", "NP", "NPL", "524"),
            new Land("Nederland", "NL", "NLD", "528"),
            new Land("Nieuw-Caledonië", "NC", "NCL", "540"),
            new Land("Nieuw-Zeeland", "NZ", "NZL", "554"),
            new Land("Nicaragua", "NI", "NIC", "558"),
            new Land("Niger", "NE", "NER", "562"),
            new Land("Nigeria", "NG", "NGA", "566"),
            new Land("Niue", "NU", "NIU", "570"),
            new Land("Norfolkeiland", "NF", "NFK", "574"),
            new Land("Noordelijke Marianen", "MP", "MNP", "580"),
            new Land("Noord-Macedonië", "MK", "MKD", "807"),
            new Land("Noorwegen", "NO", "NOR", "578"),
            new Land("Oman", "OM", "OMN", "512"),
            new Land("Pakistan", "PK", "PAK", "586"),
            new Land("Palau", "PW", "PLW", "585"),
            new Land("Palestina, Staat", "PS", "PSE", "275"),
            new Land("Panama", "PA", "PAN", "591"),
            new Land("Papoea-Nieuw-Guinea", "PG", "PNG", "598"),
            new Land("Paraguay", "PY", "PRY", "600"),
            new Land("Peru", "PE", "PER", "604"),
            new Land("Filipijnen", "PH", "PHL", "608"),
            new Land("Pitcairneilanden", "PN", "PCN", "612"),
            new Land("Polen", "PL", "POL", "616"),
            new Land("Portugal", "PT", "PRT", "620"),
            new Land("Puerto Rico", "PR", "PRI", "630"),
            new Land("Qatar", "QA", "QAT", "634"),
            new Land("Réunion", "RE", "REU", "638"),
            new Land("Roemenië", "RO", "ROU", "642"),
            new Land("Rusland", "RU", "RUS", "643"),
            new Land("Rwanda", "RW", "RWA", "646"),
            new Land("Saint-Barthélemy", "BL", "BLM", "652"),
            new Land("Sint-Helena, Ascension en Tristan da Cunha", "SH", "SHN", "654"),
            new Land("Saint Kitts en Nevis", "KN", "KNA", "659"),
            new Land("Saint Lucia", "LC", "LCA", "662"),
            new Land("Saint-Martin (Franse Antillen)", "MF", "MAF", "663"),
            new Land("Saint-Pierre en Miquelon", "PM", "SPM", "666"),
            new Land("Saint Vincent en de Grenadines", "VC", "VCT", "670"),
            new Land("Samoa", "WS", "WSM", "882"),
            new Land("San Marino", "SM", "SMR", "674"),
            new Land("Sao Tomé en Principe", "ST", "STP", "678"),
            new Land("Saoedi-Arabië", "SA", "SAU", "682"),
            new Land("Senegal", "SN", "SEN", "686"),
            new Land("Servië", "RS", "SRB", "688"),
            new Land("Seychellen", "SC", "SYC", "690"),
            new Land("Sierra Leone", "SL", "SLE", "694"),
            new Land("Singapore", "SG", "SGP", "702"),
            new Land("Sint Maarten, Land", "SX", "SXM", "534"),
            new Land("Slowakije", "SK", "SVK", "703"),
            new Land("Slovenië", "SI", "SVN", "705"),
            new Land("Salomonseilanden", "SB", "SLB", "090"),
            new Land("Somalië", "SO", "SOM", "706"),
            new Land("Zuid-Afrika", "ZA", "ZAF", "710"),
            new Land("Zuid-Georgia en de Zuidelijke Sandwicheilanden", "GS", "SGS", "239"),
            new Land("Zuid-Soedan", "SS", "SSD", "728"),
            new Land("Spanje", "ES", "ESP", "724"),
            new Land("Sri Lanka", "LK", "LKA", "144"),
            new Land("Soedan", "SD", "SDN", "729"),
            new Land("Suriname", "SR", "SUR", "740"),
            new Land("Spitsbergen en Jan Mayen", "SJ", "SJM", "744"),
            new Land("Zweden", "SE", "SWE", "752"),
            new Land("Zwitserland", "CH", "CHE", "756"),
            new Land("Syrië", "SY", "SYR", "760"),
            new Land("Taiwan (Republiek China)", "TW", "TWN", "158"),
            new Land("Tadzjikistan", "TJ", "TJK", "762"),
            new Land("Tanzania, Verenigde Republiek", "TZ", "TZA", "834"),
            new Land("Thailand", "TH", "THA", "764"),
            new Land("Oost-Timor", "TL", "TLS", "626"),
            new Land("Togo", "TG", "TGO", "768"),
            new Land("Tokelau", "TK", "TKL", "772"),
            new Land("Tonga", "TO", "TON", "776"),
            new Land("Trinidad en Tobago", "TT", "TTO", "780"),
            new Land("Tunesië", "TN", "TUN", "788"),
            new Land("Turkije", "TR", "TUR", "792"),
            new Land("Turkmenistan", "TM", "TKM", "795"),
            new Land("Turks- en Caicoseilanden", "TC", "TCA", "796"),
            new Land("Tuvalu", "TV", "TUV", "798"),
            new Land("Oeganda", "UG", "UGA", "800"),
            new Land("Oekraïne", "UA", "UKR", "804"),
            new Land("Verenigde Arabische Emiraten", "AE", "ARE", "784"),
            new Land("Verenigd Koninkrijk", "GB", "GBR", "826"),
            new Land("Verenigde Staten", "US", "USA", "840"),
            new Land("Kleine Afgelegen Eilanden van de Verenigde Staten", "UM", "UMI", "581"),
            new Land("Uruguay", "UY", "URY", "858"),
            new Land("Oezbekistan", "UZ", "UZB", "860"),
            new Land("Vanuatu", "VU", "VUT", "548"),
            new Land("Venezuela, Bolivariaanse Republiek", "VE", "VEN", "862"),
            new Land("Vietnam", "VN", "VNM", "704"),
            new Land("Britse Maagdeneilanden", "VG", "VGB", "092"),
            new Land("Amerikaanse Maagdeneilanden", "VI", "VIR", "850"),
            new Land("Wallis en Futuna", "WF", "WLF", "876"),
            new Land("Westelijke Sahara", "EH", "ESH", "732"),
            new Land("Jemen", "YE", "YEM", "887"),
            new Land("Zambia", "ZM", "ZMB", "894"),
            new Land("Zimbabwe", "ZW", "ZWE", "716"),
            new Land("Ålandseilanden", "AX", "ALA", "248")
        };
    }
}
