using System;

namespace ISO3166NL
{
    public class Country
    {
        public string Naam { get; private set; }
        public string TweeLetterCode { get; private set; }
        public string DrieLetterCode { get; private set; }
        public string NumeriekeCode { get; private set; }

        private Country(string naam, string tweeLetterCode, string drieLetterCode, string numeriekeCode)
        {
            Naam = naam;
            TweeLetterCode = tweeLetterCode;
            DrieLetterCode = drieLetterCode;
            NumeriekeCode = numeriekeCode;
        }

        public static readonly Country[] List = new[]
        {
            new Country("Afghanistan", "AF", "AFG", "004"),
            new Country("Albanië", "AL", "ALB", "008"),
            new Country("Algerije", "DZ", "DZA", "012"),
            new Country("Amerikaans-Samoa", "AS", "ASM", "016"),
            new Country("Andorra", "AD", "AND", "020"),
            new Country("Angola", "AO", "AGO", "024"),
            new Country("Anguilla", "AI", "AIA", "660"),
            new Country("Antarctica", "AQ", "ATA", "010"),
            new Country("Antigua en Barbuda", "AG", "ATG", "028"),
            new Country("Argentinië", "AR", "ARG", "032"),
            new Country("Armenië", "AM", "ARM", "051"),
            new Country("Aruba", "AW", "ABW", "533"),
            new Country("Australië", "AU", "AUS", "036"),
            new Country("Oostenrijk", "AT", "AUT", "040"),
            new Country("Azerbeidzjan", "AZ", "AZE", "031"),
            new Country("Bahama's", "BS", "BHS", "044"),
            new Country("Bahrein", "BH", "BHR", "048"),
            new Country("Bangladesh", "BD", "BGD", "050"),
            new Country("Barbados", "BB", "BRB", "052"),
            new Country("Wit-Rusland", "BY", "BLR", "112"),
            new Country("België", "BE", "BEL", "056"),
            new Country("Belize", "BZ", "BLZ", "084"),
            new Country("Benin", "BJ", "BEN", "204"),
            new Country("Bermuda", "BM", "BMU", "060"),
            new Country("Bhutan", "BT", "BTN", "064"),
            new Country("Bolivië, De Plurinationale Staat", "BO", "BOL", "068"),
            new Country("Bonaire, Sint Eustatius en Saba", "BQ", "BES", "535"),
            new Country("Bosnië en Herzegovina", "BA", "BIH", "070"),
            new Country("Botswana", "BW", "BWA", "072"),
            new Country("Bouveteiland", "BV", "BVT", "074"),
            new Country("Brazilië", "BR", "BRA", "076"),
            new Country("Brits Indische Oceaanterritorium", "IO", "IOT", "086"),
            new Country("Brunei", "BN", "BRN", "096"),
            new Country("Bulgarije", "BG", "BGR", "100"),
            new Country("Burkina Faso", "BF", "BFA", "854"),
            new Country("Burundi", "BI", "BDI", "108"),
            new Country("Kaapverdië", "CV", "CPV", "132"),
            new Country("Cambodja", "KH", "KHM", "116"),
            new Country("Kameroen", "CM", "CMR", "120"),
            new Country("Canada", "CA", "CAN", "124"),
            new Country("Kaaimaneilanden", "KY", "CYM", "136"),
            new Country("Centraal-Afrikaanse Republiek", "CF", "CAF", "140"),
            new Country("Tsjaad", "TD", "TCD", "148"),
            new Country("Chili", "CL", "CHL", "152"),
            new Country("China", "CN", "CHN", "156"),
            new Country("Kersteiland", "CX", "CXR", "162"),
            new Country("Cocoseilanden", "CC", "CCK", "166"),
            new Country("Colombia", "CO", "COL", "170"),
            new Country("Comoren", "KM", "COM", "174"),
            new Country("Congo-Brazzaville", "CG", "COG", "178"),
            new Country("Democratische Republiek Congo", "CD", "COD", "180"),
            new Country("Cookeilanden", "CK", "COK", "184"),
            new Country("Costa Rica", "CR", "CRI", "188"),
            new Country("Ivoorkust", "CI", "CIV", "384"),
            new Country("Kroatië", "HR", "HRV", "191"),
            new Country("Cuba", "CU", "CUB", "192"),
            new Country("Curaçao", "CW", "CUW", "531"),
            new Country("Cyprus", "CY", "CYP", "196"),
            new Country("Tsjechië", "CZ", "CZE", "203"),
            new Country("Denemarken", "DK", "DNK", "208"),
            new Country("Djibouti", "DJ", "DJI", "262"),
            new Country("Dominica", "DM", "DMA", "212"),
            new Country("Dominicaanse Republiek", "DO", "DOM", "214"),
            new Country("Ecuador", "EC", "ECU", "218"),
            new Country("Egypte", "EG", "EGY", "818"),
            new Country("El Salvador", "SV", "SLV", "222"),
            new Country("Equatoriaal-Guinea", "GQ", "GNQ", "226"),
            new Country("Eritrea", "ER", "ERI", "232"),
            new Country("Estland", "EE", "EST", "233"),
            new Country("Swaziland", "SZ", "SWZ", "748"),
            new Country("Ethiopië", "ET", "ETH", "231"),
            new Country("Falklandeilanden (Islas Malvinas)", "FK", "FLK", "238"),
            new Country("Faeröer Eilanden", "FO", "FRO", "234"),
            new Country("Fiji", "FJ", "FJI", "242"),
            new Country("Finland", "FI", "FIN", "246"),
            new Country("Frankrijk", "FR", "FRA", "250"),
            new Country("Frans-Guyana", "GF", "GUF", "254"),
            new Country("Frans-Polynesië", "PF", "PYF", "258"),
            new Country("Franse Zuidelijke en Antarctische Gebieden", "TF", "ATF", "260"),
            new Country("Gabon", "GA", "GAB", "266"),
            new Country("Gambia", "GM", "GMB", "270"),
            new Country("Georgië", "GE", "GEO", "268"),
            new Country("Duitsland", "DE", "DEU", "276"),
            new Country("Ghana", "GH", "GHA", "288"),
            new Country("Gibraltar", "GI", "GIB", "292"),
            new Country("Griekenland", "GR", "GRC", "300"),
            new Country("Groenland", "GL", "GRL", "304"),
            new Country("Grenada", "GD", "GRD", "308"),
            new Country("Guadeloupe", "GP", "GLP", "312"),
            new Country("Guam", "GU", "GUM", "316"),
            new Country("Guatemala", "GT", "GTM", "320"),
            new Country("Guernsey", "GG", "GGY", "831"),
            new Country("Guinee", "GN", "GIN", "324"),
            new Country("Guinee-Bissau", "GW", "GNB", "624"),
            new Country("Guyana", "GY", "GUY", "328"),
            new Country("Haïti", "HT", "HTI", "332"),
            new Country("Heard en MacDonaldeilanden", "HM", "HMD", "334"),
            new Country("Vaticaanstad", "VA", "VAT", "336"),
            new Country("Honduras", "HN", "HND", "340"),
            new Country("Hongkong, Speciale bestuurlijke regio van Volksrepubliek China", "HK", "HKG", "344"),
            new Country("Hongarije", "HU", "HUN", "348"),
            new Country("IJsland", "IS", "ISL", "352"),
            new Country("India", "IN", "IND", "356"),
            new Country("Indonesië", "ID", "IDN", "360"),
            new Country("Iran", "IR", "IRN", "364"),
            new Country("Irak", "IQ", "IRQ", "368"),
            new Country("Ierland", "IE", "IRL", "372"),
            new Country("Man-eiland", "IM", "IMN", "833"),
            new Country("Israël", "IL", "ISR", "376"),
            new Country("Italië", "IT", "ITA", "380"),
            new Country("Jamaica", "JM", "JAM", "388"),
            new Country("Japan", "JP", "JPN", "392"),
            new Country("Jersey", "JE", "JEY", "832"),
            new Country("Jordanië", "JO", "JOR", "400"),
            new Country("Kazachstan", "KZ", "KAZ", "398"),
            new Country("Kenia", "KE", "KEN", "404"),
            new Country("Kiribati", "KI", "KIR", "296"),
            new Country("Korea, Democratische Volksrepubliek (Noord-Korea)", "KP", "PRK", "408"),
            new Country("Korea, Republiek (Zuid-Korea)", "KR", "KOR", "410"),
            new Country("Koeweit", "KW", "KWT", "414"),
            new Country("Kirgizië", "KG", "KGZ", "417"),
            new Country("Laos", "LA", "LAO", "418"),
            new Country("Letland", "LV", "LVA", "428"),
            new Country("Libanon", "LB", "LBN", "422"),
            new Country("Lesotho", "LS", "LSO", "426"),
            new Country("Liberia", "LR", "LBR", "430"),
            new Country("Libië", "LY", "LBY", "434"),
            new Country("Liechtenstein", "LI", "LIE", "438"),
            new Country("Litouwen", "LT", "LTU", "440"),
            new Country("Luxemburg", "LU", "LUX", "442"),
            new Country("Macau, Speciale bestuurlijke regio van Volksrepubliek China", "MO", "MAC", "446"),
            new Country("Madagaskar", "MG", "MDG", "450"),
            new Country("Malawi", "MW", "MWI", "454"),
            new Country("Maleisië", "MY", "MYS", "458"),
            new Country("Maldiven", "MV", "MDV", "462"),
            new Country("Mali", "ML", "MLI", "466"),
            new Country("Malta", "MT", "MLT", "470"),
            new Country("Marshalleilanden", "MH", "MHL", "584"),
            new Country("Martinique", "MQ", "MTQ", "474"),
            new Country("Mauritanië", "MR", "MRT", "478"),
            new Country("Mauritius", "MU", "MUS", "480"),
            new Country("Mayotte", "YT", "MYT", "175"),
            new Country("Mexico", "MX", "MEX", "484"),
            new Country("Micronesia, Federale staten van", "FM", "FSM", "583"),
            new Country("Moldavië, Republiek", "MD", "MDA", "498"),
            new Country("Monaco", "MC", "MCO", "492"),
            new Country("Mongolië", "MN", "MNG", "496"),
            new Country("Montenegro", "ME", "MNE", "499"),
            new Country("Montserrat", "MS", "MSR", "500"),
            new Country("Marokko", "MA", "MAR", "504"),
            new Country("Mozambique", "MZ", "MOZ", "508"),
            new Country("Myanmar", "MM", "MMR", "104"),
            new Country("Namibië", "NA", "NAM", "516"),
            new Country("Nauru", "NR", "NRU", "520"),
            new Country("Nepal", "NP", "NPL", "524"),
            new Country("Nederland", "NL", "NLD", "528"),
            new Country("Nieuw-Caledonië", "NC", "NCL", "540"),
            new Country("Nieuw-Zeeland", "NZ", "NZL", "554"),
            new Country("Nicaragua", "NI", "NIC", "558"),
            new Country("Niger", "NE", "NER", "562"),
            new Country("Nigeria", "NG", "NGA", "566"),
            new Country("Niue", "NU", "NIU", "570"),
            new Country("Norfolkeiland", "NF", "NFK", "574"),
            new Country("Noordelijke Marianen", "MP", "MNP", "580"),
            new Country("Noord-Macedonië", "MK", "MKD", "807"),
            new Country("Noorwegen", "NO", "NOR", "578"),
            new Country("Oman", "OM", "OMN", "512"),
            new Country("Pakistan", "PK", "PAK", "586"),
            new Country("Palau", "PW", "PLW", "585"),
            new Country("Palestina, Staat", "PS", "PSE", "275"),
            new Country("Panama", "PA", "PAN", "591"),
            new Country("Papoea-Nieuw-Guinea", "PG", "PNG", "598"),
            new Country("Paraguay", "PY", "PRY", "600"),
            new Country("Peru", "PE", "PER", "604"),
            new Country("Filipijnen", "PH", "PHL", "608"),
            new Country("Pitcairneilanden", "PN", "PCN", "612"),
            new Country("Polen", "PL", "POL", "616"),
            new Country("Portugal", "PT", "PRT", "620"),
            new Country("Puerto Rico", "PR", "PRI", "630"),
            new Country("Qatar", "QA", "QAT", "634"),
            new Country("Réunion", "RE", "REU", "638"),
            new Country("Roemenië", "RO", "ROU", "642"),
            new Country("Rusland", "RU", "RUS", "643"),
            new Country("Rwanda", "RW", "RWA", "646"),
            new Country("Saint-Barthélemy", "BL", "BLM", "652"),
            new Country("Sint-Helena, Ascension en Tristan da Cunha", "SH", "SHN", "654"),
            new Country("Saint Kitts en Nevis", "KN", "KNA", "659"),
            new Country("Saint Lucia", "LC", "LCA", "662"),
            new Country("Saint-Martin (Franse Antillen)", "MF", "MAF", "663"),
            new Country("Saint-Pierre en Miquelon", "PM", "SPM", "666"),
            new Country("Saint Vincent en de Grenadines", "VC", "VCT", "670"),
            new Country("Samoa", "WS", "WSM", "882"),
            new Country("San Marino", "SM", "SMR", "674"),
            new Country("Sao Tomé en Principe", "ST", "STP", "678"),
            new Country("Saoedi-Arabië", "SA", "SAU", "682"),
            new Country("Senegal", "SN", "SEN", "686"),
            new Country("Servië", "RS", "SRB", "688"),
            new Country("Seychellen", "SC", "SYC", "690"),
            new Country("Sierra Leone", "SL", "SLE", "694"),
            new Country("Singapore", "SG", "SGP", "702"),
            new Country("Sint Maarten, Land", "SX", "SXM", "534"),
            new Country("Slowakije", "SK", "SVK", "703"),
            new Country("Slovenië", "SI", "SVN", "705"),
            new Country("Salomonseilanden", "SB", "SLB", "090"),
            new Country("Somalië", "SO", "SOM", "706"),
            new Country("Zuid-Afrika", "ZA", "ZAF", "710"),
            new Country("Zuid-Georgia en de Zuidelijke Sandwicheilanden", "GS", "SGS", "239"),
            new Country("Zuid-Soedan", "SS", "SSD", "728"),
            new Country("Spanje", "ES", "ESP", "724"),
            new Country("Sri Lanka", "LK", "LKA", "144"),
            new Country("Soedan", "SD", "SDN", "729"),
            new Country("Suriname", "SR", "SUR", "740"),
            new Country("Spitsbergen en Jan Mayen", "SJ", "SJM", "744"),
            new Country("Zweden", "SE", "SWE", "752"),
            new Country("Zwitserland", "CH", "CHE", "756"),
            new Country("Syrië", "SY", "SYR", "760"),
            new Country("Taiwan (Republiek China)", "TW", "TWN", "158"),
            new Country("Tadzjikistan", "TJ", "TJK", "762"),
            new Country("Tanzania, Verenigde Republiek", "TZ", "TZA", "834"),
            new Country("Thailand", "TH", "THA", "764"),
            new Country("Oost-Timor", "TL", "TLS", "626"),
            new Country("Togo", "TG", "TGO", "768"),
            new Country("Tokelau", "TK", "TKL", "772"),
            new Country("Tonga", "TO", "TON", "776"),
            new Country("Trinidad en Tobago", "TT", "TTO", "780"),
            new Country("Tunesië", "TN", "TUN", "788"),
            new Country("Turkije", "TR", "TUR", "792"),
            new Country("Turkmenistan", "TM", "TKM", "795"),
            new Country("Turks- en Caicoseilanden", "TC", "TCA", "796"),
            new Country("Tuvalu", "TV", "TUV", "798"),
            new Country("Oeganda", "UG", "UGA", "800"),
            new Country("Oekraïne", "UA", "UKR", "804"),
            new Country("Verenigde Arabische Emiraten", "AE", "ARE", "784"),
            new Country("Verenigd Koninkrijk", "GB", "GBR", "826"),
            new Country("Verenigde Staten", "US", "USA", "840"),
            new Country("Kleine Afgelegen Eilanden van de Verenigde Staten", "UM", "UMI", "581"),
            new Country("Uruguay", "UY", "URY", "858"),
            new Country("Oezbekistan", "UZ", "UZB", "860"),
            new Country("Vanuatu", "VU", "VUT", "548"),
            new Country("Venezuela, Bolivariaanse Republiek", "VE", "VEN", "862"),
            new Country("Vietnam", "VN", "VNM", "704"),
            new Country("Britse Maagdeneilanden", "VG", "VGB", "092"),
            new Country("Amerikaanse Maagdeneilanden", "VI", "VIR", "850"),
            new Country("Wallis en Futuna", "WF", "WLF", "876"),
            new Country("Westelijke Sahara", "EH", "ESH", "732"),
            new Country("Jemen", "YE", "YEM", "887"),
            new Country("Zambia", "ZM", "ZMB", "894"),
            new Country("Zimbabwe", "ZW", "ZWE", "716"),
            new Country("Ålandseilanden", "AX", "ALA", "248")
        };
    }
}
